site_name: WingChecker Documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - content.tabs.link
    - navigation.top
  language: en 
  logo: images/logo.png
  favicon: images/favicon.ico
  custom_dir: overrides
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode



copyright: Copyright &copy; 2024 Mitja Jančič

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/distractor/WingChecker_Documentation

plugins:
  - glightbox
  - search

nav:
  - Home: index.md
  - Installation: installation/installation.md
  - Manual:
    - Manual for Production: manual/manual_production.md
    - Manual for Checkers: manual/manual.md
  - About:
    - Release Notes: about/release_notes.md
    - Contributing: about/contributing.md
    - License: about/license.md
  - Support: support/support.md

extra:
  consent:
    title: Cookie consent
    description: > # (1)
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.