site_name: WingChecker Documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - content.tabs.link
    - navigation.top
  language: en 
  logo: images/logo.png
  favicon: images/favicon.ico



copyright: Copyright &copy; 2024 Mitja Jančič

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/distractor/WingChecker_Documentation

plugins:
  - glightbox
  - search

nav:
  - Home: index.md
  - Installation: installation/installation.md
  - Manual:
    - Manual for Production: manual/manual_production.md
    - Manual for Checkers: manual/manual.md
  - About:
    - Release Notes: about/release_notes.md
    - Contributing: about/contributing.md
    - License: about/license.md
  - Support: support/support.md