site_name: WingChecker documentation

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - django

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Manual:
    - Manual for production: manual/manual_production.md
    - Manual for checkers: manual/manual.md
  - About:
    - Release Notes: about/release_notes.md
    - Contributing: about/contributing.md
    - License: about/license.md