site_name: WingChecker documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - content.tabs.link

copyright: Copyright &copy; 2024 Mitja Jančič

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://github.com/distractor/WingChecker_Documentation

extra:
  generator: false

plugins:
  - glightbox
  - search
  
nav:
  - Home: index.md
  - Installation: installation/installation.md
  - Manual:
    - Manual for Production: manual/manual_production.md
    - Manual for Checkers: manual/manual.md
  - About:
    - Release Notes: about/release_notes.md
    - Contributing: about/contributing.md
    - License: about/license.md
  - Support: support/support.md